### ISSUE TITLE
Support multiple datasets in a repository

### ISSUE THREAD

**Issue by timwis** [JarvusInnovations/gitsheets#24]
They should be inside folders named after the dataset, each with their own config file, e.g.

```
.gitsheets/
  students.toml
  teachers.toml
students/
  1
  2
teachers/
  1
  2
```

**Comment by themightychris** [comment]
To add to that, each sheet config should have a configuable root and path template, e.g.

```toml
[gitsheet]
root = "slate/students"
path = "{{ graduation_year }}/{{ status }}/{{ student_number }}"
```

This will provide a lot of flexibility for integration gitsheet storage into any project, and opens the door to a submodule-compatible solution for referencing arbitrary remote gitsheet datasets
