### ISSUE TITLE
Copy GitHub Actions syntax for path templates

### ISSUE THREAD

**Issue by themightychris** [JarvusInnovations/gitsheets#34]
Either using some npm module or our own code, let's switch now to hewing closely to (but not worrying about compatibility with) the syntax GitHub Actions uses: https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#about-context-and-expressions

e.g.

```toml
[gitsheet]
root = "slate/students"
path = "${{ graduation_year }}/${{ status }}/${{ student_number }}"
```

We're pretty close already anyway, and I think we're going to have a need eventually to support some basic functions like Actions does that I was trying to figure out a syntax for (e.g. to use a prefix of or split a field value into multiple path components to keep tree sizes down), so we might as well piggy-back on GitHub
